// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_layout.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/signout.ts";
import * as $5 from "./routes/signup.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_layout.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/signout.ts": $4,
    "./routes/signup.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
